service: sls-numpy-pandas-template
app: sls-templates

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  profile: zfc_admin

functions:
  hello:
    handler: handler.hello
    layers:
      - Ref: PythonRequirementsLambdaLayer

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    zip: true
    layer: true
    noDeploy:
      - pytest
      - exceptiongroup
      - iniconfig
      - packaging
      - pluggy
      - tomli

package:
  exclude:
    - node_modules/**
    - venv/**

plugins:
  - serverless-python-requirements
